# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - main: ./main
    id: "gencli"
    binary: ./bin/gencli
    env:
      - CGO_ENABLED=0
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-apple-darwin20.2-clang{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
        {{- end }}

    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags: 
      - -mod=vendor
    ldflags:
      - -X github.com/AISocietyIITJ/gencli/pkg.Version={{ .Version }}
    igmore: 
      - goos: windows
      - goarch: arm64

checksums:
  name_template: "checksums.txt"

nfpms:
  - package_name: gencli
    vendor: AISocietyIITJ
    homepage: https://github.com/AISocietyIITJ/gencli
    maintainer: Lakshya Jain <lakshyajainrj19@gmail.com>
    license: MIT
    formats:
      - deb
      - archlinux
      - rpm
    release: "1"
    bindir: /usr
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/gencli/LICENSE
      - src: README.md
        dst: /usr/share/doc/gencli/README.md
    
release:
  prerelease: auto
  github:
    owner: AISocietyIITJ
    name: gencli
  name_template: "{{.ProjectName}}-v{{.Version}}"

archives:
  - wrap_in_directory: false
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
aurs:
  - name: gencli-bin
    homepage: https://github.com/AISocietyIITJ/gencli
    description: "GenCLI - A Gemini-Powered interactable CLI for fast, accurate file search."
    license: MIT
    maintainers:
      - "Lakshya Jain <lakshyajainrj19@gmail.com>"
    contributors:
      - "Lakshya Jain <lakshyajainrj19@gmail.com>"
    commit_author:
      name: lakshyajain-0291
      email: lakshyajainrj19@gmail.com
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/gencli-bin.git"
    package: |-
      install -Dm755 "./bin/gencli" "${pkgdir}/usr/bin/gencli"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/gencli/LICENSE"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/gencli/README.md"

brews:
  - name: gencli
    url_template: "https://github.com/AISocietyIITJ/gencli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: lakshyajain-0291
      email: lakshyajainrj19@gmail.com
    commit_msg_template: "Brew formula update for gencli version {{ .Tag }}"
    homepage: "https://github.com/AISocietyIITJ/gencli"
    description: "GenCLI - A Gemini-Powered interactable CLI for fast, accurate file search."
    license: "MIT"
    skip_upload: false
    install: |
        bin.install "bin/gencli"
    repository:
      owner: AISocietyIITJ
      name: homebrew-gencli
      branch: main
      pull_request:
        enabled: false

scoops:
  - name: gencli
    url_template: "https://github.com/AISocietyIITJ/gencli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: lakshyajain-0291
      email: lakshyajainrj19@gmail.com
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/AISocietyIITJ/gencli"
    description: "GenCLI - A Gemini-Powered interactable CLI for fast, accurate file search."
    license: MIT
    skip_upload: false
    repository:
      owner: AISocietyIITJ
      name: scoop-gencli
      branch: main
      pull_request:
        enabled: false